# Generated by Django 2.2.2 on 2019-06-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.CharField(max_length=2000)),
                ('var2', models.DateTimeField(verbose_name='date post')),
            ],
        ),
    ]
