# Generated by Django 2.2.2 on 2019-07-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('comments', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Donation_center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('center_mobile', models.CharField(max_length=20)),
                ('center_telephone', models.CharField(max_length=20)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('update_to_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_first_name', models.CharField(max_length=30)),
                ('do_last_name', models.CharField(max_length=60)),
                ('blood_group', models.CharField(choices=[('O+', 'O positif'), ('O-', 'O negatif'), ('A+', 'A positif'), ('A-', 'A negatif'), ('B+', 'B positif'), ('B-', 'B negatif'), ('AB+', 'AB positif'), ('AB-', 'AB negatif')], max_length=2)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('Autre', 'Autre')], max_length=6)),
                ('cnts_id', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('donation_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodApp.Donation_center')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Campaign_center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodApp.Donation_center')),
            ],
        ),
        migrations.CreateModel(
            name='Blood_bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity', models.DateField()),
                ('enter_date', models.DateField()),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodApp.Donation')),
                ('donation_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodApp.Donation_center')),
            ],
        ),
    ]
